# Generated by Django 4.0.2 on 2022-09-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
    ]
