# Generated by Django 4.0.2 on 2022-10-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_post_options_city_likes_alter_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=100)),
                ('last_name', models.CharField(default='last name', max_length=100)),
                ('username', models.CharField(default='last name', max_length=100)),
                ('bio', models.TextField()),
                ('email', models.CharField(default='last name', max_length=100)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('city', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
